// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB00Pcs-NSYDc-wrHfpt16KYIHtfdlO8lc',
    appId: '1:52572140506:web:04ae395364a5d0ccfd06e3',
    messagingSenderId: '52572140506',
    projectId: 'restaurantrecodeapp',
    authDomain: 'restaurantrecodeapp.firebaseapp.com',
    storageBucket: 'restaurantrecodeapp.appspot.com',
    measurementId: 'G-N0ZNKXP50P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZEBI2MLiAemCMxH4dKc3HPQc26BpJnA',
    appId: '1:52572140506:android:a876dd8e8f03c760fd06e3',
    messagingSenderId: '52572140506',
    projectId: 'restaurantrecodeapp',
    storageBucket: 'restaurantrecodeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYISEelYKdKThWumXNQpMsiELTqyCC00U',
    appId: '1:52572140506:ios:905d9350876406c1fd06e3',
    messagingSenderId: '52572140506',
    projectId: 'restaurantrecodeapp',
    storageBucket: 'restaurantrecodeapp.appspot.com',
    iosClientId: '52572140506-eofbf7v0n8iaf6mjmr9n6t3k22ro2drt.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantRecodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYISEelYKdKThWumXNQpMsiELTqyCC00U',
    appId: '1:52572140506:ios:254f76c564afe916fd06e3',
    messagingSenderId: '52572140506',
    projectId: 'restaurantrecodeapp',
    storageBucket: 'restaurantrecodeapp.appspot.com',
    iosClientId: '52572140506-hbtaetm3qnosrb2l6kn20ee0p0kv0iqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantRecodeApp.RunnerTests',
  );
}
